### ISSUE TITLE
RFC: New governance structure

### ISSUE THREAD

**Issue by gavinhenderson** [dasher-project/governance#1]
# Summary

I am putting forward a new governance structure for all dasher projects as well as a new code of conduct.

Here are links to the documents:
* [Governance Document](https://github.com/dasher-project/governance/blob/main/README.md)
* [Code Of Conduct](https://github.com/dasher-project/governance/blob/main/code-of-conduct.md)

# Motivation

The motivation behind the governance structure is to formalise the current structure that is currently implicitly held. Making it explicit makes it easy for people to understand rather than having to guess.

The motivation behind a code of conduct is showing our commitment to create a safe environment for contributors and users of Dasher.

# Drawbacks

The governance document might need more explanations in the future and is subjective in some places but it is meant as a starting point. It can evolve over time as our needs do. I also don't want to get bogged down in process, the governance should help us not hinder us.

# Any questions?

I would love to hear any questions or concerns or if there is anything you think needs changed. This RFC will follow the process outlined in the governance document. If you agree with the new governance document let me know too

**Comment by willwade** [comment]
Well thought out and clearly written. I cant see any issues personally..  Great stuff Gavin. 

One thought I guess..  do we need to outline the aims of dasher anywhere? I guess thats not for this..

**Comment by gavinhenderson** [comment]
> One thought I guess.. do we need to outline the aims of dasher anywhere? I guess thats not for this..

Yeah we definitely should, although lets not tie it to the governance structure, the governance should stay the same even if we change our aims. 

Need to rethink where we keep docs like that. Im on it.
